spring:
  application:
    name: eureka
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  devtools:
    add-properties: true

sgd:
  eureka:
    auth:
      u: admin
      p: admin

#eureka:
#  instance:
  # 是否以ip方式注册。默认false。若设置成true，则defaultZone中应使用ip，而不是hostname。单机多节点时不能使用ip注册，会造成ip重复，以致无法注册成功
#    prefer-ip-address: true
#  server:
    # 自我保护机制开关。默认开启，表示若服务出现心跳丢失，eureka不会立即将其从注册列表剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 30000
#    peer-node-read-timeout-ms: 1000
#  client:
    # 是否注册自己。默认true
#    register-with-eureka: true
    # 是否从其他eureka节点获取注册信息。默认true
#    fetch-registry: true
#  dashboard:
    #是否启用eureka web界面。默认true
#    enabled: true

---
spring:
  profiles: aaa

server:
  port: 18001

eureka:
  instance:
    # hostname不能一样
    hostname: eureka01
    # 实例名默认为 hostname:serviceName
    instance-id: eureka18001
  client:
    service-url:
      defaultZone: http://${sgd.eureka.auth.u}:${sgd.eureka.auth.p}@eureka02:18001/eureka/

---
spring:
  profiles: bbb

server:
  port: 18002

eureka:
  instance:
    hostname: eureka02
    # 实例名默认为 hostname:serviceName
    instance-id: eureka18002
  client:
    service-url:
      defaultZone: http://${sgd.eureka.auth.u}:${sgd.eureka.auth.p}@eureka01:18001/eureka/