spring:
  application:
    name: provider
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  devtools:
    add-properties: true

server:
  servlet:
    context-path: /provider

sgd:
  eureka:
    auth:
      u: admin
      p: admin

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${sgd.eureka.auth.u}:${sgd.eureka.auth.p}@eureka01:18001/eureka/

# actuator 的端点开放
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: aaa

server:
  port: 18101

eureka:
  instance:
    # hostname不能一样
    hostname: provider01
    # 实例名默认为 hostname
    instance-id: provider18101

---
spring:
  profiles: bbb

server:
  port: 18102

eureka:
  instance:
    # hostname不能一样
    hostname: provider02
    # 实例名默认为 hostname:serviceName
    instance-id: provider18102
